easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Programme
        - App\Entity\Evenement
        - App\Entity\Reservation
        - App\Entity\User
        - App\Entity\Enfant
        - App\Entity\Carousel
